import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from './components/header';
import { getServerSession } from 'next-auth';
import SessionProvider from '../app/components/sessionProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang='en'>
      <SessionProvider session={session}>
        <body className={`flex flex-col inter ${inter.className}`}>
          <Header />
          <main className='flex flex-col flex-1'>{children}</main>
        </body>
      </SessionProvider>
    </html>
  );
}
